services:
  postgres:
    image: postgres:16
    container_name: controlplane-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: controlplane
      POSTGRES_PASSWORD: controlplane
      POSTGRES_DB: controlplane

    ports:
      - "5433:5432"

    volumes:
      - controlplane_postgres_data:/var/lib/postgresql/data
      - ./tables/traces.sql:/docker-entrypoint-initdb.d/traces.sql:ro

volumes:
  controlplane_postgres_data: